In [88]:
def is_palindrom(val):
    return val == val[::-1]

def palindrome_partition(val):
    if len(val) == 0:
        return [[]]
    values = []
    for i in range(1,len(val) + 1):
        if is_palindrom(val[:i]):
            for pal in palindrome_partition(val[i:]):
                to_add = [val[:i]]
                to_add.extend(pal)
                values.append(to_add)
    return values

palindrome_partition("aabcb")

[['a', 'a', 'b', 'c', 'b'],
 ['a', 'a', 'bcb'],
 ['aa', 'b', 'c', 'b'],
 ['aa', 'bcb']]

In [100]:
class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

        
def is_unival(root):
    if root == None:
        return True
    if root.left and root.left.val != root.val:
        return False
    if root.right and root.right.val != root.val:
        return False
    return is_unival(root.left) and is_unival(root.right)

def count_unival_subtrees(root):
    if root == None:
        return 0
    left_count = count_unival_subtrees(root.left)
    right_count = count_unival_subtrees(root.right)
    if not is_unival(root.left) or not is_unival(root.left) or \
    (root.left and root.left.val != root.val) or  \
    (root.right and root.right.val != root.val):
        return left_count + right_count
    return left_count + right_count + 1
        
    
# Example 1
root = TreeNode(5)
root.left = TreeNode(1)
root.right = TreeNode(5)
root.left.left = TreeNode(5)
root.left.right = TreeNode(5)
root.right.right = TreeNode(5)
count_unival_subtrees(root)

4

In [106]:
class Node:
    def __init__(self, val=None, next=None, child=None):
        self.val = val
        self.next = next
        self.child = child

def remove_na(lst):
    while lst.next is not None:
        if lst.next.val is None:
            lst.next = lst.next.next
        lst = lst.next
        

def print_nodes(lst):
    while lst is not None:
        print(lst.val)
        lst=lst.next
    
def remove_None(lst):
    while ____(1)____:
        if ____(2)____ is None:
            ____(3)____ = ____(4)____
        ____(5)____

node10 = Node(10)
node8 = Node(8, child=node10)
node7 = Node(7, next=node8)

node4 = Node(4)
node3 = Node(None, next=node4)

node2 = Node(2, next=node3, child=node7)
node1 = Node(1, next=node2)
print_nodes(node1)
remove_na(node1)
print_nodes(node1)


1
2
None
4
1
2
4


In [1]:
import math
def f3(n):
    s = (n/2) * (n/3) * (n/4) * (n/5)
    for i in range (int(s * math.log(n^2))):
        if i < math.log(n):
            print (n)
        else:
            break
    for j in range(2 * n):
        for t in range(j):
            print(n)


In [59]:
import numpy as np
kernel = np.array([
    [1,0,1],
    [0,0,0],
    [1,0,1]
])

life_threshold = 2
overcrowding_threshold = 4
orig_board =np.array( [
                [0, 0, 0, 1, 0, 0],
            	[0, 0, 0, 1, 0, 0],
		    	[0, 1, 1, 0, 1, 0],
    			[0, 0, 0, 1, 0, 0],
    			[0, 0, 0, 1, 0, 0],])
number_of_rounds = 6

def run_round(orig_board,kernel,life_threshold,overcrowding_threshold):
    board = np.pad(orig_board,1)
    height,width =board.shape[0],board.shape[1]
    kernel_height,kernel_width = kernel.shape[0],kernel.shape[1]
    new_img = np.zeros((height-kernel_height+1,width-kernel_width+1)) 
    
    for i in range(kernel_height//2, height-kernel_height//2-1):
        for j in range(kernel_width//2, width-kernel_width//2-1):
            window = board[i-kernel_height//2 : i+kernel_height//2+1,j-kernel_width//2 : j+kernel_width//2+1]        
            if np.sum(window*kernel) >= life_threshold and np.sum(window*kernel) < overcrowding_threshold:
                new_img[i-1, j-1] = 1
    return new_img.astype(np.uint8)

def game_of_life_advanced(board,kernel,gen,life_threshold=2,overcrowding_threshold=4):
    curr_board = board
    for i in range(gen):
        curr_board = run_round(curr_board,kernel,life_threshold,overcrowding_threshold)
    return curr_board
for i in range(number_of_rounds):
    print("iteration",i)
    print(game_of_life_advanced(orig_board,kernel,i))
    print()

iteration 0
[[0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 1 1 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]]

iteration 1
[[0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 1 0 1 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]]

iteration 2
[[0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 1 1 1 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]]

iteration 3
[[0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 1 0 1 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]]

iteration 4
[[0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 1 1 1 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]]

iteration 5
[[0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 1 0 1 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]]



In [72]:
kernel = np.array([
    [1,1,1],
    [0,0,0],
    [1,1,1]
])

life_threshold = 2
overcrowding_threshold = 5
orig_board =np.array( [
                [1, 1, 1, 1, 0, 1],
            	[0, 0, 0, 0, 0, 0],
		    	[1, 1, 1, 1, 0, 1],
    			[0, 0, 0, 0, 0, 0],
    			[0, 1, 0, 1, 1, 1],])
number_of_rounds = 1
print(game_of_life_advanced(orig_board,kernel,number_of_rounds,life_threshold,overcrowding_threshold))

[[0 0 0 0 0 0]
 [1 0 0 1 1 0]
 [0 0 0 0 0 0]
 [1 1 0 1 0 0]
 [0 0 0 0 0 0]]


In [113]:
# print(board)
def find_percentile(arr: np.ndarray, p: float) -> float:
    sorted_arr = sorted(arr)
    print(sorted_arr)
    is_integer = ((len(arr) - 1) * p/100).is_integer()
    if is_integer:
        return sorted_arr[int(((len(arr) - 1) * p/100))]
    a = sorted_arr[int(((len(arr) - 1) * p/100))]
    b = sorted_arr[int(((len(arr) - 1) * p/100)) + 1]
    return (a+b)/2
print(find_percentile(np.array([3.2, 1.5, 2.8, 4.1,3.0]),60))
print(find_percentile(np.array([1000, 1, 500, 300,200]),40))

    

[1.5, 2.8, 3.0, 3.2, 4.1]
3.1
[1, 200, 300, 500, 1000]
250.0


In [5]:
for i in range(30600,30900,10):
    print(f"p{i}_i0")
    print(f"p{i}_i1")

p30600_i0
p30600_i1
p30610_i0
p30610_i1
p30620_i0
p30620_i1
p30630_i0
p30630_i1
p30640_i0
p30640_i1
p30650_i0
p30650_i1
p30660_i0
p30660_i1
p30670_i0
p30670_i1
p30680_i0
p30680_i1
p30690_i0
p30690_i1
p30700_i0
p30700_i1
p30710_i0
p30710_i1
p30720_i0
p30720_i1
p30730_i0
p30730_i1
p30740_i0
p30740_i1
p30750_i0
p30750_i1
p30760_i0
p30760_i1
p30770_i0
p30770_i1
p30780_i0
p30780_i1
p30790_i0
p30790_i1
p30800_i0
p30800_i1
p30810_i0
p30810_i1
p30820_i0
p30820_i1
p30830_i0
p30830_i1
p30840_i0
p30840_i1
p30850_i0
p30850_i1
p30860_i0
p30860_i1
p30870_i0
p30870_i1
p30880_i0
p30880_i1
p30890_i0
p30890_i1
